// BERT-style WordPiece tokenizer feeding embed.rs. Adapted from Telegraph's
// public MIT-licensed baseline
// (github.com/telegraphprotocol/telegraph-wasm-baseline/src/tokenizer.rs),
// with only the real_weights code path kept (this project always wants real
// embeddings, no projection-fallback mode).

extern crate alloc;

use alloc::string::String;
use alloc::vec::Vec;

pub const TOKEN_CLS: u32 = 101;
pub const TOKEN_SEP: u32 = 102;
pub const TOKEN_PAD: u32 = 0;
pub const TOKEN_UNK: u32 = 100;

/// MiniLM-L6-v2 maximum sequence length (model hard limit).
pub const MAX_SEQ_LEN: usize = 128;

const MAX_TOKEN_LEN: usize = 48; // must match build.rs's MAX_TOKEN_LEN
const RECORD_SIZE: usize = 2 + 4 + MAX_TOKEN_LEN;
const MAX_INPUT_CHARS_PER_WORD: usize = 200;

// Pre-generated by build_vocab_table.mjs (run once, offline) instead of a
// build.rs -- this machine has no working host C/C++ linker, and Cargo
// build scripts always need one to compile+run regardless of the actual
// wasm32-unknown-unknown target, so avoiding build.rs entirely sidesteps
// that rather than requiring a multi-GB toolchain install. Same output
// format Telegraph's own build.rs produces (sorted, fixed 54-byte records),
// just generated offline once and committed as a static asset.
static VOCAB_TABLE: &[u8] = include_bytes!("../../vocab_table.bin");

pub struct Encoding {
    pub input_ids: Vec<u32>,
    pub attention_mask: Vec<u32>,
}

/// Tokenise `text` into a padded BERT encoding of length `MAX_SEQ_LEN`.
///
/// Splits and tokenizes words one at a time and stops as soon as enough
/// tokens are collected, rather than first building a Vec of every word in
/// the whole input (as an earlier version of this function did via a
/// separate split_words() pass) -- a pathologically long stress-test input
/// (Stage 1's "survives long input without crashing" check) could contain
/// far more words than MAX_SEQ_LEN ever needs, and collecting all of them
/// up front through this module's bump-only internal allocator (see
/// lib.rs's BumpAllocator -- it never frees) exhausted the internal heap
/// before tokenization even got to use only the first ~127 of them,
/// crashing on a genuinely valid Stage 1 test case (registrationId 249).
pub fn tokenize(text: &str) -> Encoding {
    let mut ids: Vec<u32> = Vec::with_capacity(MAX_SEQ_LEN);
    ids.push(TOKEN_CLS);

    let mut current = String::new();
    'chars: for ch in text.chars() {
        if ids.len() >= MAX_SEQ_LEN - 1 {
            break 'chars;
        }
        if ch.is_alphanumeric() {
            // A single word with no delimiters at all (no whitespace/
            // punctuation) never hits the branch below that flushes
            // `current`, so it needs its own bound -- otherwise a huge
            // delimiter-free stress-test string (e.g. one giant blob with
            // no spaces) would grow `current` without limit before ever
            // reaching a word boundary. wordpiece_tokenize already treats
            // anything over MAX_INPUT_CHARS_PER_WORD as a single [UNK], so
            // stop accumulating once that's guaranteed regardless.
            if current.chars().count() < MAX_INPUT_CHARS_PER_WORD {
                current.push(if ch.is_ascii_uppercase() {
                    (ch as u8 + 32) as char
                } else {
                    ch
                });
            }
        } else if !current.is_empty() {
            for id in wordpiece_tokenize(&current) {
                if ids.len() >= MAX_SEQ_LEN - 1 {
                    break 'chars;
                }
                ids.push(id);
            }
            current.clear();
        }
    }
    if !current.is_empty() {
        for id in wordpiece_tokenize(&current) {
            if ids.len() >= MAX_SEQ_LEN - 1 {
                break;
            }
            ids.push(id);
        }
    }

    ids.push(TOKEN_SEP);

    let seq_len = ids.len();
    ids.resize(MAX_SEQ_LEN, TOKEN_PAD);

    let attention_mask: Vec<u32> = (0..MAX_SEQ_LEN)
        .map(|i| if i < seq_len { 1 } else { 0 })
        .collect();

    Encoding {
        input_ids: ids,
        attention_mask,
    }
}

/// Greedy longest-match-first WordPiece, matching BERT's reference
/// algorithm: repeatedly take the longest matching prefix (continuation
/// pieces after the first are prefixed `##`); if no split is found, the
/// whole word becomes a single [UNK].
fn wordpiece_tokenize(word: &str) -> Vec<u32> {
    let chars: Vec<char> = word.chars().collect();
    if chars.is_empty() {
        return Vec::new();
    }
    if chars.len() > MAX_INPUT_CHARS_PER_WORD {
        return alloc::vec![TOKEN_UNK];
    }

    let mut sub_tokens: Vec<u32> = Vec::new();
    let mut start = 0usize;

    while start < chars.len() {
        let mut end = chars.len();
        let mut found: Option<u32> = None;

        while start < end {
            let piece: String = if start == 0 {
                chars[start..end].iter().collect()
            } else {
                let mut s = String::from("##");
                s.extend(chars[start..end].iter());
                s
            };
            if let Some(id) = lookup_token(&piece) {
                found = Some(id);
                break;
            }
            end -= 1;
        }

        match found {
            Some(id) => {
                sub_tokens.push(id);
                start = end;
            }
            None => return alloc::vec![TOKEN_UNK],
        }
    }

    sub_tokens
}

/// Binary search VOCAB_TABLE for `tok`. O(log vocab_size), no allocation.
fn lookup_token(tok: &str) -> Option<u32> {
    let needle = tok.as_bytes();
    if needle.len() > MAX_TOKEN_LEN {
        return None;
    }

    let n = VOCAB_TABLE.len() / RECORD_SIZE;
    let mut lo = 0usize;
    let mut hi = n;

    while lo < hi {
        let mid = lo + (hi - lo) / 2;
        let rec = &VOCAB_TABLE[mid * RECORD_SIZE..(mid + 1) * RECORD_SIZE];
        let len = u16::from_le_bytes([rec[0], rec[1]]) as usize;
        let rec_tok = &rec[6..6 + len];

        match needle.cmp(rec_tok) {
            core::cmp::Ordering::Less => hi = mid,
            core::cmp::Ordering::Greater => lo = mid + 1,
            core::cmp::Ordering::Equal => {
                return Some(u32::from_le_bytes([rec[2], rec[3], rec[4], rec[5]]));
            }
        }
    }

    None
}
